gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#b15c00"
      - "bold"
    inactiveBorderColor:
      - "#4094a3"
    searchingActiveBorderColor:
      - "#b15c00"
      - "bold"
    optionsTextColor:
      - "#2e7de9"
    selectedLineBgColor:
      - "#b7c1e3"
    cherryPickedCommitFgColor:
      - "#2e7de9"
    cherryPickedCommitBgColor:
      - "#9854f1"
    markedBaseCommitFgColor:
      - "#2e7de9"
    markedBaseCommitBgColor:
      - "#8c6c3e"
    unstagedChangesColor:
      - "#c64343"
    defaultFgColor:
      - "#3760bf"  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  showIcons: false # deprecated: use nerdFontsVersion instead
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
os:
  editCommand: 'nvim'
confirmOnQuit: true
disableStartupPopups: true
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
