gui:
  border: rounded
  theme:
    activeBorderColor:
      - '#ef9f76'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#ef9f76'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'
  authorColors:
    '*': '#babbf1'  
  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  showIcons: false # deprecated: use nerdFontsVersion instead
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
os:
  editCommand: 'nvim'
confirmOnQuit: true
disableStartupPopups: true
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
