# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 
# Learn how to configure: https://wiki.hyprland.org/Configuring/

# ==================
# STARTUP APPS
# ==================
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
exec-once = hyprdynamicmonitors run
exec-once = hypridle

# Auto delete trash 30 days old
exec-once = trash-empty 30

source = ./dms/animations.conf
source = ./dms/decoration.conf
source = ./dms/device.conf
source = ./dms/dwindle.conf
source = ./dms/environment.conf
source = ./dms/general.conf
source = ./dms/gestures.conf
source = ./dms/group.conf
source = ./dms/input.conf
source = ./dms/master.conf
source = ./dms/misc.conf
source = ./dms/windowrule.conf
source = ./dms/xwayland.conf

source = ./dms/rules/dms.conf
source = ./dms/rules/hyprshot.conf
source = ./dms/rules/jetbrains.conf
source = ./dms/rules/localsend.conf
source = ./dms/rules/pip.conf

# Auto generated by dms
source = ./dms/colors.conf
source = ./dms/outputs.conf
source = ./dms/layout.conf
source = ./dms/cursor.conf
source = ./dms/binds.conf
