gui:
  border: rounded
  theme:
    activeBorderColor:
      - '#fabd2f'
      - bold
    inactiveBorderColor:
      - '#7c6f64'
    selectedLineBgColor:
      - '#3c3836'
    optionsTextColor:
      - '#83a598'
